apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseer
  labels:
    name: overseer
spec:
  rules:
    - host: overseer.vkolobara.home
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: overseer
                port:
                  number: 8989
